// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa8pKkqaOJBNTQ7fTQgxHWBIhqnDaybB4',
    appId: '1:1024489975688:web:8598dcf3a442455104d43d',
    messagingSenderId: '1024489975688',
    projectId: 'feedback-form-app-32885',
    authDomain: 'feedback-form-app-32885.firebaseapp.com',
    databaseURL: 'https://feedback-form-app-32885-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'feedback-form-app-32885.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcnEVECOq1TjzOThb-PVuE_tVzBN-88aM',
    appId: '1:1024489975688:android:86c3449c213c351104d43d',
    messagingSenderId: '1024489975688',
    projectId: 'feedback-form-app-32885',
    databaseURL: 'https://feedback-form-app-32885-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'feedback-form-app-32885.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzw3GjnTdJU1NrDwzIe0bpjmWgtd6H5V4',
    appId: '1:1024489975688:ios:0724043af34c95b104d43d',
    messagingSenderId: '1024489975688',
    projectId: 'feedback-form-app-32885',
    databaseURL: 'https://feedback-form-app-32885-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'feedback-form-app-32885.appspot.com',
    iosBundleId: 'com.example.feedbackFormApp',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzw3GjnTdJU1NrDwzIe0bpjmWgtd6H5V4',
    appId: '1:1024489975688:ios:db09d2a24625177b04d43d',
    messagingSenderId: '1024489975688',
    projectId: 'feedback-form-app-32885',
    databaseURL: 'https://feedback-form-app-32885-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'feedback-form-app-32885.appspot.com',
    iosBundleId: 'com.example.feedbackFormApp.RunnerTests',
  );
}
